services:
  - type: cron
    name: betclic-scraper
    runtime: docker
    region: frankfurt
    plan: starter
    schedule: "0 5,13,21 * * *"  # Exécution à 5h, 13h, et 21h tous les jours
    dockerCommand: python betclic_scraper_render_optimized.py
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SCRAPERAPI_KEY
        sync: false
        
  - type: cron
    name: player-stats-scraper
    runtime: docker
    region: frankfurt
    plan: starter
    schedule: "0 3 * * *"  # Exécution à 3h du matin tous les jours
    dockerCommand: python player_stats_scraper.py
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false 
